name: Sachora-WhatsApp-Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Bot (Keep Alive)
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        run: |
          while true; do
            echo "Starting bot..."
            node index.js
            echo "Bot crashed. Restarting in 5 seconds..."
            sleep 5
          done
